name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-package-java:
    name: Test et Package
    runs-on: ubuntu-latest

    steps:
    - name: Ficher courant
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Cache SonarQube packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Maven Package
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')