name: Généré Documentation

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  generation-java-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'

      - name: Créer Javadoc
        run: mvn -B javadoc:javadoc

      - name: Deployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs